### ISSUE TITLE
Playground sometimes gets confused

### ISSUE THREAD

**Issue by topaxi** [cssnext/cssnext#165] opened 2015-06-24 16:14 UTC
I'm not really sure when it happens, but sometimes the playground does weird things.

All I can say, I'm deleting the initial stuff and pasting in the new css.

Here side by side comparison:
![playground-bug](https://cloud.githubusercontent.com/assets/213788/8335228/b6a2502c-1a9c-11e5-83ff-a40bc63b4e91.png)

Tested in Firefox 41.0a1

**Comment by topaxi** [comment] 2015-06-24 16:18
In the first tab I got this console warning: Warning: The selector ':--fizzbuzz' is undefined in CSS!

But even if I repaste the same snippet, it's compiled wrong and a new warning appears, works fine in a fresh tab though...

**Comment by MoOx** [comment] 2015-06-24 16:20
It might be related to the plugin. Maybe a memory issue. This is weird.

**Comment by topaxi** [comment] 2015-06-24 16:24
Yeah, maybe I shouldn't browse with nightlies...

I'll try to use a plain stable Firefox with a new profile for the playground for the next days and report if I can reproduce this.

**Comment by topaxi** [comment] 2015-06-26 07:26
Okay I reproduced this now with the following code:

```css
@custom-selector :--foo .foo;

:--foo {
  color: bar;
}
```

After that, I **type** a new `@custom-selector`:

```css
@custom-selector :--foo .foo;
@custom-selector :--bar .bar;

:--foo {
  color: bar;
}
```

If I now use `:--bar` it will be "undefined" and the following happens:

Input:
```css
@custom-selector :--foo .foo;
@custom-selector :--bar .bar;

:--foo :--bar {
  color: bar;
}
```
Output:
```css
.foo {
  color: bar;
}
```

Tested in Firefox 38 and a completely new profile (no addons etc.)

**Comment by MoOx** [comment] 2015-06-29 04:37
I cannot reproduce :/

![screen shot 2015-06-29 at 06 36 36](https://cloud.githubusercontent.com/assets/157534/8401052/3e637e8e-1e29-11e5-8d6d-4df13c033671.png)

**Comment by topaxi** [comment] 2015-06-29 05:49
Mh weird, I'll try on other machines later this day. I can still reproduce this on my notebook on either Firefox or Chrome.

Note: I can't reproduce this if I copy&paste the second custom-selector, if there is some debouncing, maybe I'm typing slower than you..?

**Comment by MoOx** [comment] 2015-06-29 05:53
Ok I totally reproduced it. It seems the module that handle custom selectors have a weird memory management.

**Comment by MoOx** [comment] 2015-06-29 13:28
Closing since the appropriate issue is opened on the right module https://github.com/postcss/postcss-custom-selectors/issues/19
It seems related to this part https://github.com/postcss/postcss-custom-selectors/blob/e020e3220644d1975b4dc7102d1acb1e0bec38a0/index.js#L21 which does not reset the list for each plugin executions

**Closed by MoOx** 2015-06-29 13:28 UTC
Labels: status: need investigation, type: bug
