### ISSUE TITLE
Cannot use cssnext with postcss-cli

### ISSUE THREAD

**Issue by dfcreative** [cssnext/cssnext#98] opened 2015-04-22 11:40 UTC
Hello. I see basic-case error on ubuntu, using cssnext as a postcss plugin.
postcss@4.1.5 is installed globally.
cssnext@1.3.0 is installed globally.

`index.css`:
```css
body {
	background: linear-gradient(red, gray);
}
```

Running 
`$ postcss -u cssnext index.css -o bundle.css`

returns

`[TypeError: object is not a function]`

Why?

**Comment by MoOx** [comment] 2015-04-22 11:45
Can you provide the stacktrace please ?

**Comment by MoOx** [comment] 2015-04-22 11:48
I cannot reproduce it on the playground http://cssnext.github.io/cssnext-playground/

**Comment by dfcreative** [comment] 2015-04-22 13:05
Stacktrace from postcss-cli error callback:
```
TypeError: object is not a function
    at LazyResult.run (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:152:24)
    at LazyResult.asyncTick (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:80:29)
    at processing.Promise.then._this2.processed (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:106:20)
    at LazyResult.async (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:105:27)
    at LazyResult.then (/usr/local/lib/node_modules/postcss-cli/node_modules/postcss/lib/lazy-result.js:68:21)
    at doProcess (/usr/local/lib/node_modules/postcss-cli/index.js:83:14)
    at iterate (/usr/local/lib/node_modules/postcss-cli/node_modules/neo-async/lib/async.js:2248:18)
    at /usr/local/lib/node_modules/postcss-cli/node_modules/neo-async/lib/async.js:2272:11
    at process._tickCallback (node.js:355:11)

```

**Comment by MoOx** [comment] 2015-04-22 13:28
I am guessing it's more a postcss-cli bug or a integration to improve.
poke @ai @code42day

**Comment by dfcreative** [comment] 2015-04-22 13:32
Yep. Found that https://github.com/code42day/postcss-cli/blob/master/index.js#L52 contains strange result of parsing: `[ { plugins: [ [Function], ... ]}]`, which seems to be extra wrapped.
Unwrapping it like `plugins = plugins[0].plugins` solves the trouble, still can't find why.

**Comment by dfcreative** [comment] 2015-04-22 13:41
@MoOx it seems that it's still cssnext's issue, as autoprefixer and any other plugin works just fine, whereas cssnext fails.
I've found that [here](https://github.com/code42day/postcss-cli/blob/master/index.js#L57) autoprefixer and others returns [Function], whereas cssnext returns object containing list of plugins: `{plugins: [Function], [Function], ...}`

**Comment by MoOx** [comment] 2015-04-24 05:00
cssnext is a postcss instance already (because it's not "just" a plugin, but a wrapper that use plugins).
postcss core accept that to be used (see passing tests https://github.com/cssnext/cssnext/blob/12ae1f320fd23f8590d880cad7f18d1bde889146/test/api.js#L22-L25)

So I think it's more a postcss-cli issue, really. @code42day can you take a look please ?

**Comment by MoOx** [comment] 2015-04-27 04:09
I've created an issue on postcss-cli about that https://github.com/code42day/postcss-cli/issues/11

**Comment by MoOx** [comment] 2015-05-01 04:02
Does this helps ? https://github.com/postcss/postcss/releases/tag/4.1.8

**Comment by MoOx** [comment] 2015-05-03 22:40
Closed by https://github.com/postcss/postcss/commit/57a8d4fa771fbca9f4976f586b455545f87f21f4

**Closed by MoOx** 2015-05-03 22:40 UTC
Labels: type: bug
