### ISSUE TITLE
Custom Selectors sometimes generate REALLY unexpected output

### ISSUE THREAD

**Issue by awayken** [cssnext/cssnext#178] opened 2015-07-02 18:00 UTC
I don't really know to explain this one except by example. It may be related to #177, which I just submitted, but it also might be unrelated.

Input:
```css
@custom-selector :--buttons button, input[type="button"];
@custom-selector :--hovers :hover, .hover;

:--buttons:--hovers {
    background: color(#ff9800 shade(20%));
}

button:--hovers,
input[type="button"]:--hover {
    background: color(#ff9800 shade(20%));
}
```

Output:
```css
:hover:--hovers,
.hover:--hovers {
    background: rgb(204, 122, 0);
}

:hover,
.hover
input[type="button"]:hover,

input[type="button"].hover {
    background: rgb(204, 122, 0);
}
```

**Comment by topaxi** [comment] 2015-07-02 18:01
Duplicate of #163 and postcss/postcss-custom-selectors#19 and #177

**Comment by awayken** [comment] 2015-07-02 18:04
@topaxi Since this ticket (and #177) do seem related to the postcss issue, do we keep them open until that task is completed and we can test that these examples work as expected? Or do we close these as duplicates?

**Comment by topaxi** [comment] 2015-07-02 18:04
@awayken that is up to the maintainers of cssnext i guess :)

**Comment by awayken** [comment] 2015-07-02 18:06
@topaxi All right. I'll leave my tickets as submitted for now, and I'll subscribe to the postcss ticket to get updates on progress.

**Comment by MoOx** [comment] 2015-07-03 10:24
Please follow #163.

**Closed by MoOx** 2015-07-03 10:24 UTC
