### ISSUE TITLE
Update autoprefixer-core to the latest version to remove console warnings

### ISSUE THREAD

**Issue by piotrkulpinski** [cssnext/cssnext#229] opened 2015-10-20 08:55 UTC
Hi there,
I'm getting following warnings while using cssnext:
```
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Node#removeSelf is deprecated. Use Node#remove.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Node#before is deprecated. Use Node#raws.before
```

I found out that it's related to autoprefixer itself and it was fixed in v6 of the package, but cssnext still uses the old v5 version.

Here's the reference: https://github.com/postcss/autoprefixer/issues/500

**Comment by ben-eb** [comment] 2015-10-20 09:01
Duplicate of https://github.com/cssnext/cssnext/issues/202.

**Comment by piotrkulpinski** [comment] 2015-10-20 09:02
That one is closed already and I don't see my issue resolved there so I think it should stay for now.

**Comment by ben-eb** [comment] 2015-10-20 09:06
See also https://github.com/cssnext/cssnext/issues/208.

**Comment by MoOx** [comment] 2015-10-20 17:40
Please see #230

**Closed by MoOx** 2015-10-20 17:40 UTC
